### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by techker** [princeolivier78/M3U-Loader-for-Live-Channels-App#1]
Hey, is the source available for the loader app?im learning on tv dev and would like a guide to see how it works..

Thx

**Comment by princeolivier78** [comment]
Hi sorry for the late reply it's not an open source but it's based on the
live channels app from Google in android tv theres an open sample :)

**Comment by princeolivier78** [comment]
Here Mike here's the sample from Google

https://github.com/googlesamples/androidtv-sample-inputs

**Comment by techker** [comment]
Nice Thx!

**Comment by princeolivier78** [comment]
No probs mate 👍🏾

**Comment by techker** [comment]
ya...been on it for over 1h and i can't get the channels loaded in the rich Input..when im in thelive chsnnels app- settings-channel source opens the sample app parses the channels all ok but when i click done i get a toast no channels added..uhh..
thx

**Comment by princeolivier78** [comment]
Check the Internet permissions in the manifest :)

**Comment by techker** [comment]
ya its there..its like if the live vhannels app was not receiving the channels.

**Comment by princeolivier78** [comment]
The only thing I can think of is the net ,or the feeds are no
longer working,or check the clear network thing in the manifest and xml if
that don't work then I'm not sure but if you made it that far then it's has
to be a small issue

**Comment by techker** [comment]
ya thx again. il continue debuging to see.:)

**Comment by princeolivier78** [comment]
You welcome :)
